---
image_name: faas-worker
image_tag:20180620
domain: dom1

resources: 
  - name: res01
    version: v1
    functions:
      - name: get
      - name: post
      - name: put
      - name: delete

  - name: res01
    version: v2
    functions:
      - name: get

  - name: res02
    version: v1
    functions:
      - name: get
      - name: post
      - name: delete